from Bot import twitterBot


def main():
  API_KEY = "pXCwX1nrUCDxXsrdgoZk5VdEX"
  API_SECRET_KEY = "i4QraUyMWoDfccKlCAtNz4DCSHT8rJGmmkXqY7jsobEBvCSFNn"
  BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAOhogQEAAAAAe2tlGB8z22V7kG0UpIMBwHcJBBU%3DC0la8ErkBh3ke2OWIBcnq7NbLgFuWIkkZaE3zbqW8bVJOENRcT"
  ACCESS_TOKEN = "1298692051983388676-ruaPIaujU6cWnWLgt6q63ntBwcE67d"
  ACCESS_SECRET_TOKEN = "VQXvzjmlBrgWziPM9GvyznT32uLzQbgFzPnEeLFaO3Ev9"

  Bot = twitterBot(API_KEY,API_SECRET_KEY ,ACCESS_TOKEN,ACCESS_SECRET_TOKEN)
  Bot.send_tweet()


if __name__ == "__main__":
  main()